"""empty message

Revision ID: 04b9a46ca011
Revises: eec0774a210c
Create Date: 2023-05-03 01:19:01.030161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b9a46ca011'
down_revision = 'eec0774a210c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mass_dice_entry', sa.Column('issuer_nickname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mass_dice_entry', 'issuer_nickname')
    # ### end Alembic commands ###
