"""empty message

Revision ID: 6b1ce5d78cd0
Revises: 5ec23fdc42df
Create Date: 2023-07-25 22:17:54.453214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1ce5d78cd0'
down_revision = '5ec23fdc42df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('config', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('diceamount', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('diceamount', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('mass_dice_ban_record', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('mass_dice_ban_record', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('mass_dice_entry', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('mass_dice_entry', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('voteban_entry', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('voteban_entry', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voteban_entry', 'updated_at')
    op.drop_column('voteban_entry', 'created_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('mass_dice_entry', 'updated_at')
    op.drop_column('mass_dice_entry', 'created_at')
    op.drop_column('mass_dice_ban_record', 'updated_at')
    op.drop_column('mass_dice_ban_record', 'created_at')
    op.drop_column('diceamount', 'updated_at')
    op.drop_column('diceamount', 'created_at')
    op.drop_column('config', 'updated_at')
    op.drop_column('config', 'created_at')
    # ### end Alembic commands ###
