"""empty message

Revision ID: eec0774a210c
Revises: ff0d689e1f90
Create Date: 2023-05-03 00:21:43.171971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec0774a210c'
down_revision = 'ff0d689e1f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mass_dice_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('trigger_text', sa.String(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mass_dice_entry_id'), 'mass_dice_entry', ['id'], unique=False)
    op.create_index(op.f('ix_mass_dice_entry_issuer_id'), 'mass_dice_entry', ['issuer_id'], unique=False)
    op.create_table('mass_dice_ban_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_nickname', sa.String(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['mass_dice_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mass_dice_ban_record_id'), 'mass_dice_ban_record', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mass_dice_ban_record_id'), table_name='mass_dice_ban_record')
    op.drop_table('mass_dice_ban_record')
    op.drop_index(op.f('ix_mass_dice_entry_issuer_id'), table_name='mass_dice_entry')
    op.drop_index(op.f('ix_mass_dice_entry_id'), table_name='mass_dice_entry')
    op.drop_table('mass_dice_entry')
    # ### end Alembic commands ###
