"""empty message

Revision ID: f3e2b361cf2f
Revises: 04b9a46ca011
Create Date: 2023-05-03 01:42:14.814741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e2b361cf2f'
down_revision = '04b9a46ca011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diceamount', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('diceamount', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mass_dice_ban_record', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mass_dice_ban_record', 'user_nickname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mass_dice_entry', 'issuer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mass_dice_entry', 'issuer_nickname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mass_dice_entry', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mass_dice_entry', 'trigger_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mass_dice_entry', 'trigger_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mass_dice_entry', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mass_dice_entry', 'issuer_nickname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mass_dice_entry', 'issuer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mass_dice_ban_record', 'user_nickname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mass_dice_ban_record', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('diceamount', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('diceamount', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
