"""added diceamount table

Revision ID: ff0d689e1f90
Revises: ea740c4605d5
Create Date: 2023-01-11 01:55:32.774354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0d689e1f90'
down_revision = 'ea740c4605d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diceamount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diceamount_id'), 'diceamount', ['id'], unique=False)
    op.create_index(op.f('ix_diceamount_user_id'), 'diceamount', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diceamount_user_id'), table_name='diceamount')
    op.drop_index(op.f('ix_diceamount_id'), table_name='diceamount')
    op.drop_table('diceamount')
    # ### end Alembic commands ###
