"""empty message

Revision ID: 030f9fbd53c2
Revises: f1f10099fbe3
Create Date: 2025-09-17 15:56:27.362595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030f9fbd53c2'
down_revision = 'f1f10099fbe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("mass_dice_ban_record", "trovo_backend_mass_dice_ban_record")
    op.rename_table("mass_dice_entry", "trovo_backend_mass_dice_entry")
    op.rename_table("track", "trovo_backend_track")
    op.rename_table("voteban_entry", "trovo_backend_voteban_entry")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("trovo_backend_mass_dice_ban_record", "mass_dice_ban_record")
    op.rename_table("trovo_backend_mass_dice_entry", "mass_dice_entry")
    op.rename_table("trovo_backend_track", "track")
    op.rename_table("trovo_backend_voteban_entry", "voteban_entry")
    # ### end Alembic commands ###
