"""empty message

Revision ID: 469b06664e5e
Revises: f3e2b361cf2f
Create Date: 2023-05-30 14:15:06.825518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469b06664e5e'
down_revision = 'f3e2b361cf2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mass_dice_ban_record', sa.Column('message', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mass_dice_ban_record', 'message')
    # ### end Alembic commands ###
