"""empty message

Revision ID: 5ec23fdc42df
Revises: 601ab2497383
Create Date: 2023-07-22 03:24:58.125365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec23fdc42df'
down_revision = '601ab2497383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mass_dice_entry', sa.Column('ascii_target_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mass_dice_entry', 'ascii_target_role')
    # ### end Alembic commands ###
