"""empty message

Revision ID: c9dab73fec16
Revises: 469b06664e5e
Create Date: 2023-06-14 21:32:09.694240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9dab73fec16'
down_revision = '469b06664e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voteban_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('target_nickname', sa.String(), nullable=False),
    sa.Column('issuer_user_id', sa.Integer(), nullable=False),
    sa.Column('issuer_nickname', sa.String(), nullable=False),
    sa.Column('votes_needed', sa.Integer(), nullable=False),
    sa.CheckConstraint('votes_needed > 0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voteban_entry_id'), 'voteban_entry', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voteban_entry_id'), table_name='voteban_entry')
    op.drop_table('voteban_entry')
    # ### end Alembic commands ###
