"""empty message

Revision ID: f1f10099fbe3
Revises: 112b9b40d800
Create Date: 2025-09-17 15:48:32.809532

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f1f10099fbe3"
down_revision = "112b9b40d800"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("config", "trovo_backend_config")
    op.rename_table("diceamount", "trovo_backend_diceamount")
    op.rename_table("user", "trovo_backend_user")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("trovo_backend_config", "config")
    op.rename_table("trovo_backend_diceamount", "diceamount")
    op.rename_table("trovo_backend_user", "user")
    # ### end Alembic commands ###
